### ISSUE TITLE
command 'ls' not working in directory containing spaces

### ISSUE THREAD

**Issue by HashtagMarkus** [bats3c/shad0w#53]
The ls command is not working in directories like `documents and settings`

The response from the beacon is

```
      ERROR: Access to the path '.\*' is denied.
```

**Comment by bats3c** [comment]
Have you tried putting the directory in quotes?

**Comment by HashtagMarkus** [comment]
Yes, here's how it doesn't work

```
shad0w(Administrator@NINJUTSU-OS) ≫ cd "C:\Documents and Settings"
[i] Beacon (5cd2c86b80b78d8a158483817b777e16) received task
Directory Changed to: 'C:\Documents and Settings'

shad0w(Administrator@NINJUTSU-OS) ≫ ls
[i] Beacon (5cd2c86b80b78d8a158483817b777e16) received task
ERROR: Access to the path '.\*' is denied.
```

while on other dirs it works

```
shad0w(Administrator@NINJUTSU-OS) ≫ cd C:\Go
[i] Beacon (5cd2c86b80b78d8a158483817b777e16) received task
Directory Changed to: 'C:\Go'

shad0w(Administrator@NINJUTSU-OS) ≫ ls
[i] Beacon (5cd2c86b80b78d8a158483817b777e16) received task
Directory: .\*

Type    Created           Last Access        Length      Name
----    -------           -----------        ------      ----
DIR     16/03/2020 05:26  24/09/2020 07:36               .
DIR     16/03/2020 05:26  24/09/2020 07:36               ..
DIR     27/07/2020 11:53  24/09/2020 07:36               api
```

**Comment by bats3c** [comment]
This is strange, will have a look into it

**Comment by bblenard** [comment]
@HashtagMarkus Does `C:\Documents and Settings\` actually exist. I looked at this in my test machine and found that `cd "C:\Documents and Settings\"` works fine however `C:\Documents and Settings` doesn't actually exist. I'm wondering if this is some strange windowism that lets you [SetCurrentDirectory](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-setcurrentdirectory) without failing but since you aren't actually in a real directory you can't read the contents of the directory which is why the ls call fails.
